package safety

import (
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// TimeField specifies which timestamp to use when evaluating file age.
// TimeField 指定在评估文件年龄时使用哪个时间戳。
type TimeField int

const (
	// TimeFieldMtime uses the file modification time for age evaluation.
	// TimeFieldMtime 使用文件修改时间进行年龄评估。
	TimeFieldMtime TimeField = iota
	// TimeFieldCtime uses the file change time for age evaluation.
	// TimeFieldCtime 使用文件状态变更时间进行年龄评估。
	TimeFieldCtime
)

// Plan represents a deletion plan generated by AgePlan, tracking which entries to delete and keep.
// Plan 表示由 AgePlan 生成的删除计划，跟踪要删除和保留的条目。
type Plan struct {
	root     string
	delete   map[string]Entry
	keepDirs map[string]bool
	ordered  []Entry
}

// WillDelete returns true if the given absolute path is scheduled for deletion.
// WillDelete 如果给定绝对路径已被计划删除，则返回 true。
func (p *Plan) WillDelete(absPath string) bool {
	_, ok := p.delete[absPath]
	return ok
}

// Ordered returns the entries scheduled for deletion in safe deletion order.
// Ordered 按安全删除顺序返回计划删除的条目。
func (p *Plan) Ordered() []Entry {
	return p.ordered
}

// AgePlan analyzes the filesystem tree and creates a deletion plan based on file age.
// AgePlan 分析文件系统树并根据文件年龄创建删除计划。
func AgePlan(w *Walker, minAgeDays int, field TimeField, now time.Time, noAgeFilter bool) *Plan {
	threshold := now.Add(-time.Duration(minAgeDays) * 24 * time.Hour).Unix()
	var all []ageInfo
	rootAbs := w.Root()
	_ = w.Walk(func(e Entry) {
		passed := true
		if !noAgeFilter {
			ts := e.Mtime()
			if field == TimeFieldCtime {
				ts = e.Ctime()
			}
			passed = ts <= threshold
		}
		all = append(all, ageInfo{entry: e, passed: passed, absPath: filepath.Join(rootAbs, e.RelPath)})
	})

	plan := &Plan{root: rootAbs, delete: map[string]Entry{}, keepDirs: map[string]bool{}}
	for _, it := range all {
		if !it.passed {
			dir := it.absPath
			if !it.entry.IsDir() {
				dir = filepath.Dir(it.absPath)
			}
			for dir != rootAbs && dir != "/" && dir != "." {
				plan.keepDirs[dir] = true
				dir = filepath.Dir(dir)
			}
		}
	}
	for _, it := range all {
		if it.entry.IsRegular() && it.passed {
			plan.delete[it.absPath] = it.entry
		}
	}
	for _, it := range all {
		if it.entry.IsDir() && it.passed && !plan.keepDirs[it.absPath] {
			plan.delete[it.absPath] = it.entry
		}
	}
	plan.ordered = orderForDeletion(all, plan.delete)
	return plan
}

type ageInfo struct {
	entry   Entry
	passed  bool
	absPath string
}

func orderForDeletion(all []ageInfo, set map[string]Entry) []Entry {
	type pair struct {
		depth int
		e     Entry
		abs   string
	}
	var ps []pair
	for _, it := range all {
		if e, ok := set[it.absPath]; ok {
			ps = append(ps, pair{depth: pathDepth(it.absPath), e: e, abs: it.absPath})
		}
	}
	sort.SliceStable(ps, func(i, j int) bool {
		if ps[i].depth != ps[j].depth {
			return ps[i].depth > ps[j].depth
		}
		if ps[i].e.IsRegular() != ps[j].e.IsRegular() {
			return ps[i].e.IsRegular()
		}
		return ps[i].abs < ps[j].abs
	})
	out := make([]Entry, 0, len(ps))
	for _, p := range ps {
		out = append(out, p.e)
	}
	return out
}

func pathDepth(p string) int {
	return strings.Count(filepath.Clean(p), string(filepath.Separator))
}
